import * as cheerio from "cheerio";
import type { CheerioAPI } from "cheerio";
import type { CrawledPage, Finding } from "@/types/audit";
import { makeFinding } from "./finding";
import { clean } from "./page";

export function analyzeAccessibility(page: CrawledPage, document?: CheerioAPI): Finding[] {
  const $ = document ?? cheerio.load(page.html);
  const findings: Finding[] = [];
  const url = page.finalUrl;
  const html = $("html");

  if (!html.attr("lang")) findings.push(makeFinding({ category: "ux", subcategory: "language", title: "Taal van de pagina ontbreekt", description: "Schermlezers kunnen uitspraak en taalregels niet betrouwbaar bepalen.", evidence: "Het lang-attribuut ontbreekt op het html-element.", affectedUrl: url, affectedElement: "html", severity: "medium", confidence: "confirmed", source: "html", recommendation: "Declareer de primaire paginataal.", technicalImplementation: "Voeg bijvoorbeeld <html lang=\"nl\"> toe en markeer anderstalige fragmenten afzonderlijk.", estimatedEffort: "klein", acceptanceCriterion: "Het html-element bevat een geldige BCP 47-taalcode.", references: ["WCAG 3.1.1"] }));
  if (!$("meta[name='viewport']").length) findings.push(makeFinding({ category: "ux", subcategory: "mobile", title: "Viewportinstelling ontbreekt", description: "Mobiele browsers kunnen de pagina op een onjuiste schaal tonen.", evidence: "Geen meta[name=viewport] aangetroffen.", affectedUrl: url, affectedElement: "head", severity: "high", confidence: "confirmed", source: "html", recommendation: "Voeg een responsieve viewportinstelling toe.", technicalImplementation: "Gebruik <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">.", estimatedEffort: "klein", acceptanceCriterion: "De pagina heeft een viewportmeta-tag met width=device-width en een bruikbare initiële schaal." }));

  const h1Count = $("h1").length;
  if (h1Count === 0) findings.push(makeFinding({ category: "ux", subcategory: "headings", title: "Geen primaire H1-kop", description: "Een duidelijke hoofdkop helpt bezoekers en hulptechnologie de pagina te begrijpen.", evidence: "Geen h1-element aangetroffen.", affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Voeg één beschrijvende hoofdkop toe.", technicalImplementation: "Plaats een zichtbare h1 die het hoofdonderwerp van de pagina benoemt.", estimatedEffort: "klein", acceptanceCriterion: "De pagina bevat een zichtbare, unieke en beschrijvende H1.", references: ["WCAG 1.3.1", "WCAG 2.4.6"] }));
  else if (h1Count > 1) findings.push(makeFinding({ category: "ux", subcategory: "headings", title: "Meerdere H1-koppen", description: "Meerdere primaire koppen kunnen de inhoudshiërarchie onduidelijk maken.", evidence: `${h1Count} h1-elementen aangetroffen.`, affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Gebruik één duidelijke primaire kop en structureer secties met H2/H3.", technicalImplementation: "Beoordeel de documenthiërarchie en wijzig secundaire H1-elementen naar het passende niveau.", estimatedEffort: "klein", acceptanceCriterion: "De headingstructuur weerspiegelt de visuele en inhoudelijke hiërarchie." }));

  const headings = $("h1,h2,h3,h4,h5,h6").toArray().map((el) => Number(el.tagName.slice(1)));
  let skips = 0;
  headings.forEach((level, index) => { if (index > 0 && level - headings[index - 1] > 1) skips += 1; });
  if (skips) findings.push(makeFinding({ category: "ux", subcategory: "headings", title: "Kopniveaus worden overgeslagen", description: "Een onlogische headingstructuur bemoeilijkt navigatie met schermlezers.", evidence: `${skips} overgang(en) slaan een kopniveau over.`, affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Maak de koppenstructuur hiërarchisch opeenvolgend.", technicalImplementation: "Gebruik H2 onder H1, H3 onder H2 enzovoort; kies niveaus op structuur, niet op uiterlijk.", estimatedEffort: "klein", acceptanceCriterion: "Kopniveaus volgen een logische, niet-overslaande documentstructuur.", references: ["WCAG 1.3.1"] }));

  const images = $("img");
  const missingAlt = images.filter((_, el) => $(el).attr("alt") === undefined).length;
  if (missingAlt) findings.push(makeFinding({ category: "ux", subcategory: "images", title: "Afbeeldingen zonder alt-attribuut", description: "Schermlezers kunnen de functie of inhoud van deze afbeeldingen niet bepalen.", evidence: `${missingAlt} afbeelding(en) missen het alt-attribuut.`, affectedUrl: url, affectedElement: "img:not([alt])", severity: missingAlt >= 5 ? "high" : "medium", confidence: "confirmed", source: "html", recommendation: "Voeg betekenisvolle alt-tekst toe of gebruik alt=\"\" voor puur decoratieve afbeeldingen.", technicalImplementation: "Beschrijf de functie of informatie compact; vermijd bestandsnamen en redundante woorden zoals ‘afbeelding van’.", estimatedEffort: "klein", acceptanceCriterion: "Elke afbeelding heeft een passend alt-attribuut en decoratieve afbeeldingen hebben een lege alt-tekst.", references: ["WCAG 1.1.1"] }));

  const emptyButtons = $("button").filter((_, el) => !clean($(el).text()) && !$(el).attr("aria-label") && !$(el).attr("aria-labelledby") && !$(el).find("img[alt]").length).length;
  if (emptyButtons) findings.push(makeFinding({ category: "ux", subcategory: "controls", title: "Knoppen zonder toegankelijke naam", description: "Icon-only of lege knoppen zijn niet begrijpelijk voor schermlezers.", evidence: `${emptyButtons} knop(pen) zonder tekst, aria-label of andere naam.`, affectedUrl: url, affectedElement: "button", severity: "high", confidence: "confirmed", source: "html", recommendation: "Geef iedere knop een duidelijke toegankelijke naam.", technicalImplementation: "Voeg zichtbare tekst toe of gebruik aria-label/aria-labelledby dat de actie beschrijft.", estimatedEffort: "klein", acceptanceCriterion: "Elke knop heeft een unieke, actiegerichte toegankelijke naam.", references: ["WCAG 4.1.2", "WCAG 2.5.3"] }));
  const emptyLinks = $("a[href]").filter((_, el) => !clean($(el).text()) && !$(el).attr("aria-label") && !$(el).find("img[alt]").length).length;
  if (emptyLinks) findings.push(makeFinding({ category: "ux", subcategory: "links", title: "Links zonder toegankelijke naam", description: "Lege links bieden geen betekenisvolle bestemming aan hulptechnologie.", evidence: `${emptyLinks} link(s) zonder tekst of toegankelijke naam.`, affectedUrl: url, affectedElement: "a[href]", severity: "high", confidence: "confirmed", source: "html", recommendation: "Voeg een beschrijvende linknaam toe.", technicalImplementation: "Gebruik zichtbare linktekst, een betekenisvolle afbeelding-alttekst of een passende aria-label.", estimatedEffort: "klein", acceptanceCriterion: "Alle links hebben een begrijpelijke en contextspecifieke toegankelijke naam.", references: ["WCAG 2.4.4", "WCAG 4.1.2"] }));

  let unlabeledInputs = 0;
  $("input:not([type='hidden']), select, textarea").each((_, el) => {
    const id = $(el).attr("id");
    const labeled = Boolean($(el).attr("aria-label") || $(el).attr("aria-labelledby") || (id && $(`label[for='${cssEscape(id)}']`).length) || $(el).closest("label").length);
    if (!labeled) unlabeledInputs += 1;
  });
  if (unlabeledInputs) findings.push(makeFinding({ category: "ux", subcategory: "forms", title: "Formuliervelden zonder gekoppeld label", description: "Placeholders zijn geen volwaardige labels en verdwijnen tijdens invoer.", evidence: `${unlabeledInputs} veld(en) missen een labelkoppeling of toegankelijke naam.`, affectedUrl: url, affectedElement: "input,select,textarea", severity: "high", confidence: "confirmed", source: "html", recommendation: "Koppel elk veld aan een zichtbaar label.", technicalImplementation: "Gebruik label[for] met een uniek input-id, of omwikkel het veld met label; aria-label alleen wanneer een zichtbaar label niet mogelijk is.", estimatedEffort: "klein", acceptanceCriterion: "Alle invoervelden hebben een zichtbare en programmatisch gekoppelde naam.", references: ["WCAG 1.3.1", "WCAG 3.3.2", "WCAG 4.1.2"] }));

  const personalInputs = $("input[type='email'], input[type='tel'], input[name*='name' i], input[name*='address' i]");
  const noAutocomplete = personalInputs.filter((_, el) => !$(el).attr("autocomplete")).length;
  if (noAutocomplete) findings.push(makeFinding({ category: "ux", subcategory: "forms", title: "Bekende persoonsgegevens missen autocomplete", description: "Correcte autocomplete-tokens versnellen invoer en ondersteunen gebruikers met cognitieve beperkingen.", evidence: `${noAutocomplete} herkenbare persoonsveld(en) missen autocomplete.`, affectedUrl: url, severity: "low", confidence: "likely", source: "html", recommendation: "Gebruik passende autocomplete-tokens.", technicalImplementation: "Gebruik bijvoorbeeld name, email, tel, street-address, postal-code en organization volgens het veldtype.", estimatedEffort: "klein", acceptanceCriterion: "Veelgebruikte persoonsvelden hebben een semantisch correcte autocomplete-waarde.", references: ["WCAG 1.3.5"] }));

  if (!$("a[href^='#']").filter((_, el) => /(?:skip|overslaan|inhoud|content)/i.test(clean($(el).text()))).length && $("nav").length) findings.push(makeFinding({ category: "ux", subcategory: "keyboard", title: "Geen herkenbare skiplink", description: "Toetsenbordgebruikers moeten mogelijk telkens alle navigatielinks doorlopen.", evidence: "Geen herkenbare link om direct naar de hoofdinhoud te springen.", affectedUrl: url, severity: "low", confidence: "likely", source: "heuristic", recommendation: "Voeg een zichtbare skiplink bij focus toe.", technicalImplementation: "Plaats als eerste focusbaar element een link naar het id van main, bijvoorbeeld ‘Ga naar hoofdinhoud’.", estimatedEffort: "klein", acceptanceCriterion: "Bij de eerste Tab-toets verschijnt een werkende skiplink naar de hoofdinhoud.", references: ["WCAG 2.4.1"] }));

  if (!$("main").length && !$("[role='main']").length) findings.push(makeFinding({ category: "ux", subcategory: "landmarks", title: "Hoofdinhoud heeft geen main-landmark", description: "Landmarks versnellen navigatie voor schermlezers.", evidence: "Geen main-element of role=main aangetroffen.", affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Markeer de primaire inhoud als main.", technicalImplementation: "Gebruik één <main id=\"main-content\"> rond de unieke hoofdinhoud.", estimatedEffort: "klein", acceptanceCriterion: "De pagina bevat precies één duidelijke main-landmark.", references: ["WCAG 1.3.1"] }));

  const untitledFrames = $("iframe").filter((_, el) => !$(el).attr("title")).length;
  if (untitledFrames) findings.push(makeFinding({ category: "ux", subcategory: "embedded-content", title: "Iframe zonder titel", description: "Gebruikers van schermlezers weten niet welk extern onderdeel wordt ingesloten.", evidence: `${untitledFrames} iframe(s) missen een title-attribuut.`, affectedUrl: url, affectedElement: "iframe", severity: "medium", confidence: "confirmed", source: "html", recommendation: "Geef ieder iframe een korte, specifieke titel.", technicalImplementation: "Voeg title toe, bijvoorbeeld ‘Locatiekaart’ of ‘Video: …’, passend bij de inhoud.", estimatedEffort: "klein", acceptanceCriterion: "Alle iframes hebben een beschrijvende titel.", references: ["WCAG 4.1.2"] }));

  const genericLinks = $("a[href]").filter((_, el) => /^(klik hier|hier|meer|lees meer|read more|click here)$/i.test(clean($(el).text()))).length;
  if (genericLinks) findings.push(makeFinding({ category: "ux", subcategory: "links", title: "Niet-beschrijvende linkteksten", description: "Algemene teksten zoals ‘lees meer’ zijn buiten hun context onduidelijk.", evidence: `${genericLinks} link(s) gebruiken een generieke linktekst.`, affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Maak de bestemming onderdeel van de linktekst.", technicalImplementation: "Vervang bijvoorbeeld ‘Lees meer’ door ‘Lees meer over webdesign’ of voeg een toegankelijke naam met context toe.", estimatedEffort: "klein", acceptanceCriterion: "Linkteksten zijn ook in een losse linklijst begrijpelijk.", references: ["WCAG 2.4.4"] }));

  findings.push(makeFinding({ category: "ux", subcategory: "manual-testing", title: "Handmatige toegankelijkheidscontrole vereist", description: "Automatische HTML-analyse kan toetsenbordvolgorde, schermlezerervaring, visueel contrast en foutafhandeling niet volledig beoordelen.", evidence: "Deze onderdelen vereisen interactie met echte browsers en hulptechnologie.", affectedUrl: url, severity: "informational", confidence: "manual-review-required", source: "heuristic", recommendation: "Test de pagina handmatig met toetsenbord, zoom, een schermlezer en een echte smartphone.", technicalImplementation: "Doorloop alle interactieve onderdelen met Tab/Shift+Tab/Enter/Escape, test 200% zoom, valideer contrast en voltooi formulieren met fouten.", estimatedEffort: "gemiddeld", acceptanceCriterion: "Een gedocumenteerde WCAG 2.2 AA-handmatige test bevat geen blokkerende bevindingen." }));
  return findings;
}

function cssEscape(value: string): string {
  return value.replace(/['\\]/g, "\\$&");
}
