import * as cheerio from "cheerio";
import type { CheerioAPI } from "cheerio";
import type { CrawledPage, Finding } from "@/types/audit";
import { makeFinding } from "./finding";
import { clean } from "./page";

export function analyzeSeo(page: CrawledPage, document?: CheerioAPI): Finding[] {
  const $ = document ?? cheerio.load(page.html);
  const findings: Finding[] = [];
  const url = page.finalUrl;
  const title = clean($("title").first().text());
  const description = clean($("meta[name='description']").attr("content") ?? "");
  const canonical = $("link[rel~='canonical']").attr("href");
  const robots = `${$("meta[name='robots']").attr("content") ?? ""},${page.headers["x-robots-tag"] ?? ""}`.toLowerCase();
  const h1s = $("h1").map((_, el) => clean($(el).text())).get().filter(Boolean);

  if (!title) findings.push(makeFinding({ category: "seo", subcategory: "title", title: "Paginatitel ontbreekt", description: "Zoekmachines en browsergebruikers missen een primaire paginabeschrijving.", evidence: "Geen niet-lege title-tag aangetroffen.", affectedUrl: url, affectedElement: "title", severity: "high", confidence: "confirmed", source: "html", recommendation: "Voeg een unieke, relevante title-tag toe.", technicalImplementation: "Schrijf een titel die het hoofdonderwerp en waar passend het merk bevat; houd de belangrijke woorden vooraan.", estimatedEffort: "klein", acceptanceCriterion: "De pagina heeft een unieke, beschrijvende title-tag die niet generiek is." }));
  else if (title.length < 20 || title.length > 65) findings.push(makeFinding({ category: "seo", subcategory: "title", title: "Paginatitel heeft een ongunstige lengte", description: "Een zeer korte titel mist context; een lange titel kan worden afgekapt.", evidence: `Titel bevat ${title.length} tekens: “${title.slice(0, 100)}”.`, affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Maak de titel bondig en specifiek.", technicalImplementation: "Streef niet mechanisch naar een exact aantal tekens, maar plaats het onderscheidende onderwerp vroeg en vermijd herhaling.", estimatedEffort: "klein", acceptanceCriterion: "De titel beschrijft de pagina volledig en wordt in de beoogde zoekresultaatweergave niet onnodig afgekapt.", measuredValue: title.length, targetValue: "ongeveer 20–65 tekens" }));

  if (!description) findings.push(makeFinding({ category: "seo", subcategory: "meta-description", title: "Metabeschrijving ontbreekt", description: "Zoekmachines kunnen zelf een minder gerichte snippet samenstellen.", evidence: "Geen meta[name=description] met inhoud aangetroffen.", affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Schrijf een unieke beschrijving die de zoekintentie en waarde van de pagina samenvat.", technicalImplementation: "Voeg server-side een meta description toe en voorkom dat templates dezelfde tekst op meerdere pagina’s hergebruiken.", estimatedEffort: "klein", acceptanceCriterion: "De pagina heeft een unieke, relevante en overtuigende metabeschrijving." }));
  else if (description.length < 70 || description.length > 170) findings.push(makeFinding({ category: "seo", subcategory: "meta-description", title: "Metabeschrijving heeft een ongunstige lengte", description: "De beschrijving kan te weinig context geven of in zoekresultaten worden afgekapt.", evidence: `Metabeschrijving bevat ${description.length} tekens.`, affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Maak de beschrijving informatief, uniek en beknopt.", technicalImplementation: "Plaats onderwerp en voordeel vroeg; verwijder opvulling en dubbele formuleringen.", estimatedEffort: "klein", acceptanceCriterion: "De beschrijving is volledig, uniek en passend voor de belangrijkste zoekintentie.", measuredValue: description.length, targetValue: "ongeveer 70–170 tekens" }));

  if (!canonical) findings.push(makeFinding({ category: "seo", subcategory: "canonical", title: "Canonical-tag ontbreekt", description: "Varianten met parameters of alternatieve URL-vormen kunnen minder eenduidig worden geconsolideerd.", evidence: "Geen link[rel=canonical] aangetroffen.", affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Voeg een zelfverwijzende canonical toe op indexeerbare pagina’s.", technicalImplementation: "Render een absolute canonical-URL die overeenkomt met de voorkeurs-URL na redirects en normalisatie.", estimatedEffort: "klein", acceptanceCriterion: "Elke indexeerbare pagina heeft één geldige absolute canonical naar de voorkeursversie." }));
  else {
    try {
      const resolved = new URL(canonical, url);
      if (!["http:", "https:"].includes(resolved.protocol)) throw new Error();
    } catch {
      findings.push(makeFinding({ category: "seo", subcategory: "canonical", title: "Canonical-tag is ongeldig", description: "Een ongeldige canonical kan niet betrouwbaar door zoekmachines worden verwerkt.", evidence: `Canonicalwaarde: ${canonical}`, affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Gebruik een geldige absolute HTTP(S)-URL.", technicalImplementation: "Genereer de canonical vanuit de genormaliseerde publieke basis-URL en het canonieke pad.", estimatedEffort: "klein", acceptanceCriterion: "De canonical is een geldige absolute URL die met 200 reageert." }));
    }
  }

  if (/(?:^|[,\s])noindex(?:[,\s]|$)/.test(robots)) findings.push(makeFinding({ category: "seo", subcategory: "indexing", title: "Pagina bevat noindex", description: "De pagina vraagt zoekmachines om deze niet in de index op te nemen.", evidence: `Robotsinstructie: ${robots}`, affectedUrl: url, severity: "informational", confidence: "confirmed", source: page.headers["x-robots-tag"] ? "response-header" : "html", recommendation: "Bevestig dat uitsluiting bewust is.", technicalImplementation: "Verwijder noindex alleen wanneer de pagina publiek waardevol en indexeerbaar hoort te zijn; behoud het voor account-, zoek- en testpagina’s.", estimatedEffort: "klein", acceptanceCriterion: "De indexeringsinstructie stemt overeen met het bedoelde zoekmachinebeleid." }));

  if (h1s.length === 0) findings.push(makeFinding({ category: "seo", subcategory: "headings", title: "H1 ontbreekt voor het hoofdonderwerp", description: "De primaire inhoudskop ontbreekt in de HTML.", evidence: "Geen niet-lege H1 aangetroffen.", affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Voeg een unieke H1 toe die het hoofdonderwerp benoemt.", technicalImplementation: "Render de H1 als zichtbare tekst in de initiële HTML en laat deze aansluiten op title en zoekintentie.", estimatedEffort: "klein", acceptanceCriterion: "De pagina bevat één duidelijke H1 die het primaire onderwerp beschrijft." }));
  if (h1s.length > 1) findings.push(makeFinding({ category: "seo", subcategory: "headings", title: "Meerdere primaire H1-koppen", description: "Meerdere hoofdkoppen kunnen de inhoudsstructuur onnodig vertroebelen.", evidence: `${h1s.length} H1-koppen aangetroffen.`, affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Gebruik één duidelijke primaire H1 en hiërarchische subkoppen.", technicalImplementation: "Herstructureer secundaire hoofdblokken naar H2 of het semantisch passende niveau.", estimatedEffort: "klein", acceptanceCriterion: "De pagina heeft een ondubbelzinnige hoofdonderwerpstructuur." }));

  if (!$("meta[property='og:title']").length || !$("meta[property='og:description']").length || !$("meta[property='og:image']").length) findings.push(makeFinding({ category: "seo", subcategory: "social-metadata", title: "Open Graph-metadata is onvolledig", description: "Gedeelde links kunnen een onvolledige of willekeurige voorvertoning krijgen.", evidence: "Minstens één van og:title, og:description of og:image ontbreekt.", affectedUrl: url, severity: "low", confidence: "confirmed", source: "html", recommendation: "Voeg consistente sociale metadata toe.", technicalImplementation: "Render per paginatype og:title, og:description, og:url, og:type en een absolute og:image met geschikte afmetingen.", estimatedEffort: "klein", acceptanceCriterion: "De belangrijkste pagina’s leveren een correcte en unieke social-preview." }));

  if (!$("script[type='application/ld+json']").length) findings.push(makeFinding({ category: "seo", subcategory: "structured-data", title: "Geen JSON-LD structured data waargenomen", description: "De pagina biedt geen expliciete machineleesbare entiteits- of paginatypegegevens.", evidence: "Geen script[type=application/ld+json] aangetroffen.", affectedUrl: url, severity: "informational", confidence: "confirmed", source: "html", recommendation: "Voeg alleen relevante, inhoudelijk zichtbare structured data toe.", technicalImplementation: "Gebruik schema.org-typen zoals Organization, LocalBusiness, WebSite, BreadcrumbList, Article of Product waar ze werkelijk van toepassing zijn.", estimatedEffort: "gemiddeld", acceptanceCriterion: "Structured data valideert en correspondeert met zichtbare pagina-inhoud." }));

  const bodyClone = $("body").clone();
  bodyClone.find("script,style,noscript,svg").remove();
  const wordCount = clean(bodyClone.text()).split(/\s+/).filter(Boolean).length;
  if (wordCount < 120 && !/(contact|login|signin|privacy|cookie|voorwaarden|terms)/i.test(new URL(url).pathname)) findings.push(makeFinding({ category: "seo", subcategory: "content", title: "Mogelijk dunne inhoud", description: "De pagina bevat weinig tekstuele context voor zoekintentie en bezoekers.", evidence: `Ongeveer ${wordCount} zichtbare woorden in de HTML.`, affectedUrl: url, severity: "medium", confidence: "likely", source: "heuristic", recommendation: "Beoordeel of de pagina het onderwerp volledig en nuttig behandelt.", technicalImplementation: "Voeg geen opvultekst toe; beantwoord relevante vragen, toon bewijs, specificaties, werkwijze en duidelijke vervolgstappen.", estimatedEffort: "gemiddeld", acceptanceCriterion: "De pagina beantwoordt de primaire zoekintentie volledig en uniek ten opzichte van andere pagina’s.", measuredValue: wordCount }));

  const missingAlt = $("img:not([alt])").length;
  if (missingAlt) findings.push(makeFinding({ category: "seo", subcategory: "images", title: "Afbeeldingen missen alt-attributen", description: "Zoekmachines en hulptechnologie missen context bij inhoudelijke afbeeldingen.", evidence: `${missingAlt} afbeelding(en) zonder alt-attribuut.`, affectedUrl: url, severity: "medium", confidence: "confirmed", source: "html", recommendation: "Voeg passende alt-teksten toe.", technicalImplementation: "Beschrijf inhoudelijke afbeeldingen compact en gebruik lege alt-tekst voor decoratieve beelden.", estimatedEffort: "klein", acceptanceCriterion: "Alle afbeeldingen hebben een semantisch passend alt-attribuut." }));

  if (page.redirectCount > 1) findings.push(makeFinding({ category: "seo", subcategory: "redirects", title: "Meervoudige redirectketen", description: "Extra redirects vertragen crawlers en gebruikers en vergroten foutkansen.", evidence: `${page.redirectCount} redirects vóór de eind-URL ${page.finalUrl}.`, affectedUrl: page.requestedUrl, severity: "medium", confidence: "confirmed", source: "response-header", recommendation: "Laat interne links en externe voorkeurs-URL’s direct naar de eindbestemming wijzen.", technicalImplementation: "Vervang tussenstappen in serverregels en update interne links naar de uiteindelijke HTTPS-canonical.", estimatedEffort: "klein", acceptanceCriterion: "De bron-URL verwijst in maximaal één redirect naar de canonieke eind-URL.", measuredValue: page.redirectCount, targetValue: 1 }));
  return findings;
}

export function analyzeCrossPageSeo(pages: CrawledPage[]): Finding[] {
  const findings: Finding[] = [];
  const titleMap = new Map<string, string[]>();
  const descriptionMap = new Map<string, string[]>();
  for (const page of pages) {
    const $ = cheerio.load(page.html);
    const title = clean($("title").first().text()).toLowerCase();
    const description = clean($("meta[name='description']").attr("content") ?? "").toLowerCase();
    if (title) titleMap.set(title, [...(titleMap.get(title) ?? []), page.finalUrl]);
    if (description) descriptionMap.set(description, [...(descriptionMap.get(description) ?? []), page.finalUrl]);
  }
  for (const [title, urls] of titleMap) if (urls.length > 1) findings.push(makeFinding({ category: "seo", subcategory: "duplicate-metadata", title: "Dubbele paginatitels", description: "Meerdere gecrawlde pagina’s gebruiken exact dezelfde titel.", evidence: `${urls.length} pagina’s delen de titel “${title.slice(0, 120)}”.`, affectedUrl: urls[0], severity: "medium", confidence: "confirmed", source: "html", recommendation: "Maak iedere indexeerbare paginatitel uniek.", technicalImplementation: "Gebruik paginatype- en onderwerpvelden in metadata-templates en valideer op duplicaten in de contentworkflow.", estimatedEffort: "klein", acceptanceCriterion: "Alle indexeerbare gecrawlde pagina’s hebben een unieke titel." }));
  for (const [description, urls] of descriptionMap) if (urls.length > 1) findings.push(makeFinding({ category: "seo", subcategory: "duplicate-metadata", title: "Dubbele metabeschrijvingen", description: "Meerdere gecrawlde pagina’s gebruiken exact dezelfde beschrijving.", evidence: `${urls.length} pagina’s delen de metabeschrijving “${description.slice(0, 120)}”.`, affectedUrl: urls[0], severity: "low", confidence: "confirmed", source: "html", recommendation: "Schrijf unieke beschrijvingen per belangrijke pagina.", technicalImplementation: "Genereer metadata uit unieke paginavelden en voorkom algemene fallbackteksten op indexeerbare pagina’s.", estimatedEffort: "klein", acceptanceCriterion: "Belangrijke indexeerbare pagina’s hebben unieke metabeschrijvingen." }));
  return findings;
}
